[package]
name = "scroll2roll"
version = "0.3.1"
entry = "src/main.rocket"

[test]
directory = "tests"

[build]
kind = "executable"
name = "Scroll2Roll"

[native.windows-x64]
libraries = "rocket_raylib_adapter.lib;raylib.lib;opengl32.lib;winmm.lib;gdi32.lib;user32.lib;shell32.lib;ole32.lib"
library-search = ".rocketc/native"
headers = "native/rocket_raylib_adapter.h"
